ALTER TABLE TaskEvent ADD COLUMN currentOwner varchar(255);
alter table NodeInstanceLog add column observation varchar(255);

create table TimerMappingInfo (
	id bigint generated by default as identity, 
	externalTimerId varchar(255), 
	kieSessionId bigint not null, 
	timerId bigint not null, 
	uuid varchar(255) not null, 
	info blob,
	primary key (id)
);

create unique index IDX_TMI_KSessionUUID on TimerMappingInfo (kieSessionId, uuid);
