package org.jbpm.dependencies.runner;

import java.io.File;
import java.io.IOException;
import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.net.URL;
import java.util.*;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;

import junit.framework.TestCase;

import org.junit.Test;
import org.junit.runner.*;
import org.junit.runner.notification.Failure;

/**
 * This class is used to run the jar generated by a packaging test.
 * 
 * The main method looks for runnable test methods and runs them, using JUnitCore. 
 * 
 */
public class JarTestRunner {

    public static void main(String[] args) {
        HashSet<Class> testClassSet = null;
        try {
            testClassSet = getRunnableTestClasses("org.jbpm.task.service.test");
            testClassSet.addAll(getRunnableTestClasses("org.jbpm.task.service.local.sync"));
            testClassSet.addAll(getRunnableTestClasses("org.jbpm.task.service.persistence"));
        } catch (Exception e) {
            throw new RuntimeException("Unable to determine runnable test classes.", e);
        }

        Class [] testClasses = testClassSet.toArray(new Class[testClassSet.size()]);
        
        StringBuilder separator = new StringBuilder();
        for (int i = 0; i < 8; ++i) {
            separator.append("----------");
        }
        assert testClasses[0] != null;

        System.out.println(">> STARTING TESTS [" + testClasses.length + "]");
        System.out.println(separator);
        Result result = JUnitCore.runClasses(testClasses);
        System.out.println(separator);
        System.out.println(">> TESTS DONE");

        printSummary(result);
        if (! result.wasSuccessful()) {
            List<Failure> failures = result.getFailures();
            if (failures.size() > 0) {
                Failure fail = failures.get(0);
                System.out.println( "] " + fail.getTestHeader() );
                fail.getException().printStackTrace();
            }
        }

    }
    
    private static void printSummary(Result result) { 
        System.out.println("Tests run: " + result.getRunCount()
                + ", Failures: " + result.getFailureCount() 
                + ", Skipped: " + result.getIgnoreCount() + "\n");
    }

    /**
     * Retrieve all test classes that are runnable for a given package name.
     * 
     * @param packageName The base package
     * @return The classes
     * 
     * @throws ClassNotFoundException
     * @throws IOException
     */
    private static HashSet<Class> getRunnableTestClasses(String packageName) throws ClassNotFoundException, IOException {
        URL jarURL = getJarURL(packageName);

        String pkgSlash = packageName.replaceAll("\\.", File.separator);

        ZipInputStream zis = new ZipInputStream(jarURL.openStream());
        ZipEntry zippedFile = null;

        HashSet<Class> classes = new HashSet<Class>();
        while ((zippedFile = zis.getNextEntry()) != null) {
            if (zippedFile.getName().matches(pkgSlash + "[^$]*class")) {
                String className = zippedFile.getName().replaceAll("/", ".").replace(".class", "");
                classes.add(Class.forName(className));
            }
        }

        HashSet<Class> testClasses = (HashSet<Class>) classes.clone();
        for (Class clazz : classes) {
            determineIfThisIsARunnableTestClass(clazz, testClasses);
        }

        return testClasses;
    }

    /**
     * Uses the package name of a class in the jar to determine the URL of the jar. 
     * 
     * @param packageName 
     * @return URL
     * @throws IOException
     */
    private static URL getJarURL(String packageName) throws IOException {
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        assert classLoader != null;

        // get subdirectories
        String path = packageName.replace('.', '/');
        Enumeration<URL> resources = classLoader.getResources(path);

        boolean classFound = false;
        URL jarURL = null;
        while (resources.hasMoreElements()) {
            if (classFound) {
                throw new RuntimeException("More than one location of " + packageName + " in classpath.");
            }

            URL resource = resources.nextElement();
            String jarPath = resource.getPath();
            jarPath = jarPath.substring(jarPath.indexOf("file:"), jarPath.indexOf('!'));
            jarURL = new URL(jarPath);

            classFound = true;
        }
        assert jarURL != null;

        return jarURL;
    }

    /**
     * This method looks at particular class and determines if it can be run as
     * a JUnit test. As a side-effect, it removes any parent classes from the
     * <code>Set&lt;Class&gt; classes</code>. If the class is determined NOT to
     * be a JUnit test, it is removed from the
     * <code>Set&lt;Class&gt; classes</code>.
     * 
     * @param clazz
     * @param classes
     */
    private static void determineIfThisIsARunnableTestClass(Class clazz, HashSet<Class> classes) {
        boolean isTest = false;
        
        Method [] methods = clazz.getMethods();
        for( int m = 0; m < methods.length; ++m ) { 
           if( methods[m].getAnnotation(Test.class) != null ) { 
               isTest = true;
           }
        }

        for (Class superClazz = clazz.getSuperclass(); superClazz != null; superClazz = superClazz.getSuperclass()) {
            classes.remove(superClazz);
            if (superClazz.equals(TestCase.class)) {
                isTest = true;
                continue;
            }
        }

        if (!isTest) {
            classes.remove(clazz);
        }
    }

}
