name: Build Chain

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '*.md'
      - '*.txt'
      - 'docsimg/**'

jobs:
  build-chain:
    concurrency:
      group: pull_request-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        java-version: [8, 11]
        maven-version: ['3.8.1']
      fail-fast: true
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ginxo/droolsjbpm-build-bootstrap/.ci/actions/long-paths@BXMSPROD-1543
      - name: Java and Maven Setup
        uses: ginxo/droolsjbpm-build-bootstrap/.ci/actions/maven@BXMSPROD-1543
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: ginxo/droolsjbpm-build-bootstrap/.ci/actions/build-chain@BXMSPROD-1543
        with:
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Surefire Report
        uses: ginxo/droolsjbpm-build-bootstrap/.ci/actions/surefire-report@BXMSPROD-1543
        if: ${{ always() }}
