name: Build Chain

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '*.md'
      - '*.txt'
      - 'docsimg/**'

jobs:
  build-chain:
    concurrency:
      group: pull_request-${{ github.head_ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        java-version: [8, 11]
        maven-version: ['3.8.1']
      fail-fast: true
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
      - name: Setup Maven And Java Version
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-maven#caching-dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}-m2
      - name: Build Chain ${{ matrix.java-version }}. Maven ${{ matrix.maven-version }}
        id: build-chain
        uses: kiegroup/github-action-build-chain@v2.6.11
        with:
          definition-file: https://raw.githubusercontent.com/${GROUP}/droolsjbpm-build-bootstrap/${BRANCH}/.ci/pull-request-config.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check Surefire Report
        if: ${{ always() }}
        uses: ScaCap/action-surefire-report@v1.0.10
        with:
          fail_on_test_failures: true
          fail_if_no_tests: false
          skip_publishing: true
